services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  ###< doctrine/doctrine-bundle ###

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
